# Setup
title:            Seth Neller
tagline:          Website
description:      Economics Ph.D. Student <br/> University of Texas
url:              https://sethneller.github.io
baseurl:          ''

# About and contact
author:
  name:           'Seth Neller'
  url:            https://twitter.com/sethneller

github:
  repo:           https://github.com/sethneller/sethneller.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

