# Setup
title:            Seth Neller
tagline:          Website
description:      Economics Ph.D. Student </br> University of Texas </br> Email: <a href="mailto:seth.neller@gmail.com" target="_blank">seth.neller@gmail.com</a> </br> Twitter: <a href="https://twitter.com/sethneller" target="_blank">@sethneller</a>.'
url:              https://sethneller.github.io
baseurl:          ''

# About and contact
author:
  name:           'Seth Neller'
  url:            https://twitter.com/sethneller

github:
  repo:           https://github.com/sethneller/sethneller.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

