# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://sethneller.github.io
baseurl:          ''

# About and contact
author:
  name:           'Seth Neller'
  url:            https://twitter.com/sethneller

github:
  repo:           https://github.com/sethneller/sethneller.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

